---
  - id: sync-additional-dependencies
    name: Sync PCH Additional Dependencies
    description: Synchronize additional dependencies with poetry.lock
    entry: sync-dependencies
    language: python
    language_version: python3.11
    args: []
    additional_dependencies:
      - packaging
      - ruamel-yaml
      - tomli
    always_run: true
    require_serial: true
    pass_filenames: false
