---
  - id: sync-additional-dependencies
    name: Sync PCH Additional Dependencies
    description: Synchronize additional dependencies with a lockfile
    entry: sync-dependencies
    language: python
    language_version: python3.13
    args: []
    additional_dependencies:
      - packaging==26.3
      - ruamel-yaml==0.19.1
      - tomli==2.4.1
    always_run: true
    require_serial: true
    pass_filenames: false
