---
repos:
  - repo: https://github.com/worgarside/pre-commit-hooks-dependency-sync
    rev: 1.1.2
    hooks:
      - id: sync-additional-dependencies
        additional_dependencies:
          - poetry
          - packaging==24.1
          - ruamel-yaml==0.18.6
          - tomli==2.0.2

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=1000
      - id: check-case-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        args:
          - --pytest-test-first
      - id: pretty-format-json
        args:
          - --no-sort-keys
          - --autofix
          - --indent
          - '2'
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args:
          - --mapping
          - '2'
          - --sequence
          - '4'
          - --offset
          - '2'
          - --width
          - '4096'

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args:
          - --format
          - parsable
          - --strict

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
      - id: pycln
        args:
          - --all

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args:
          - --strict
          - --show-error-codes
        additional_dependencies:
          - packaging==24.1
          - tomli==2.0.2
          - ruamel-yaml==0.18.6

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli==2.0.2

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.11
    hooks:
      - id: vulture
