[tool.poetry]
name = "pre-commit-hooks-dependency-sync"
version = "0.1.0"
description = "Pre-commit hook to sync your additional dependencies with your project's environment"
authors = ["Will Garside <worgarside@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = [
  "poetry-core",
]
